[build]
  cmd = "go build -o tmp/main.exe ./cmd/main.go && tmp/main.exe"
  exclude_dir = ["vendor", "tmp", "logs"]
  include_ext = ["go", "html", "tpl", "tmpl", "yaml", "yml"]
  follow_symlink = true
  kill_before_restart = true
